{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import time\n",
    "import ipywidgets as widgets\n",
    "from IPython.display import display, clear_output, HTML\n",
    "\n",
    "# ============================================================\n",
    "# MILK PASTEURIZATION PLANT - INTERACTIVE UI SIMULATION\n",
    "# ============================================================\n",
    "\n",
    "def simulate_plant(milk_temperature=5.0, milk_level=1,\n",
    "                   balance_level=0, milk_flow_rate=2.5,\n",
    "                   milk_inlet_temperature=4.0,\n",
    "                   water_inlet_temperature=85.0,\n",
    "                   water_outlet_temperature=75.0):\n",
    "\n",
    "    output.clear_output()\n",
    "\n",
    "    with output:\n",
    "        display(HTML(\"\"\"\n",
    "        <div style=\"background:#0f172a;color:white;padding:18px;border-radius:14px;\n",
    "                    font-family:Arial;margin-bottom:14px\">\n",
    "          <div style=\"font-size:24px;font-weight:700\">\ud83e\udd5b Milk Pasteurization Plant</div>\n",
    "          <div style=\"color:#cbd5e1;margin-top:4px\">Interactive Process Control Dashboard</div>\n",
    "        </div>\n",
    "        \"\"\"))\n",
    "\n",
    "        stages = [\n",
    "            (\"01\", \"Storage Tank\", \"\ud83d\udee2\ufe0f\"),\n",
    "            (\"02\", \"Balance Tank\", \"\ud83d\udd04\"),\n",
    "            (\"03\", \"Heater\", \"\ud83d\udd25\"),\n",
    "            (\"04\", \"Holding Tube\", \"\u23f1\ufe0f\"),\n",
    "            (\"05\", \"Cooling\", \"\u2744\ufe0f\"),\n",
    "            (\"06\", \"Packaging\", \"\ud83d\udce6\")\n",
    "        ]\n",
    "\n",
    "        display(HTML(\"\"\"\n",
    "        <style>\n",
    "        .plant-flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;\n",
    "                    font-family:Arial;margin:10px 0 18px}\n",
    "        .stage{padding:10px 12px;border-radius:10px;background:#e2e8f0;\n",
    "               color:#334155;font-weight:600;text-align:center;min-width:115px}\n",
    "        .arrow{font-size:20px;color:#64748b}\n",
    "        .card{padding:14px;border-radius:12px;margin:8px 0;font-family:Arial;\n",
    "              border:1px solid #e2e8f0;background:#f8fafc}\n",
    "        .ok{border-left:5px solid #16a34a}\n",
    "        .warn{border-left:5px solid #f59e0b}\n",
    "        .danger{border-left:5px solid #dc2626}\n",
    "        .metric{display:inline-block;background:#eef2ff;border-radius:10px;\n",
    "                padding:10px 14px;margin:4px;font-family:Arial}\n",
    "        </style>\n",
    "        <div class=\"plant-flow\">\n",
    "          <div class=\"stage\">\ud83d\udee2\ufe0f Storage</div><div class=\"arrow\">\u2192</div>\n",
    "          <div class=\"stage\">\ud83d\udd04 Balance</div><div class=\"arrow\">\u2192</div>\n",
    "          <div class=\"stage\">\ud83d\udd25 Heater</div><div class=\"arrow\">\u2192</div>\n",
    "          <div class=\"stage\">\u23f1\ufe0f Holding</div><div class=\"arrow\">\u2192</div>\n",
    "          <div class=\"stage\">\u2744\ufe0f Cooling</div><div class=\"arrow\">\u2192</div>\n",
    "          <div class=\"stage\">\ud83d\udce6 Packaging</div>\n",
    "        </div>\n",
    "        \"\"\"))\n",
    "\n",
    "        # Stage 1\n",
    "        if milk_temperature > 4:\n",
    "            display(HTML(f'<div class=\"card warn\"><b>Stage 1 \u2014 Storage Tank</b><br>'\n",
    "                         f'\u26a0\ufe0f Milk temperature: {milk_temperature:.1f}\u00b0C \u2014 Cooling system ACTIVATED.<br>'\n",
    "                         f'\ud83c\udf00 Level sensor: {milk_level} \u2014 Propeller motor ON.</div>'))\n",
    "        else:\n",
    "            display(HTML(f'<div class=\"card ok\"><b>Stage 1 \u2014 Storage Tank</b><br>'\n",
    "                         f'\u2705 Milk temperature: {milk_temperature:.1f}\u00b0C \u2014 Safe.<br>'\n",
    "                         f'\ud83c\udf00 Propeller motor: {\"ON\" if milk_level else \"OFF\"}.</div>'))\n",
    "\n",
    "        # Stage 2\n",
    "        if balance_level == 1:\n",
    "            display(HTML('<div class=\"card ok\"><b>Stage 2 \u2014 Balance Tank</b><br>'\n",
    "                         '\u2705 Tank full \u2014 Inlet valve CLOSED to prevent overflow.</div>'))\n",
    "        else:\n",
    "            display(HTML('<div class=\"card warn\"><b>Stage 2 \u2014 Balance Tank</b><br>'\n",
    "                         '\u2197\ufe0f Tank level low \u2014 Inlet valve OPEN for refilling.</div>'))\n",
    "\n",
    "        # Stage 3\n",
    "        cp_milk = 3.89\n",
    "        cp_water = 4.18\n",
    "        target = 72\n",
    "        denominator = cp_water * (water_inlet_temperature - water_outlet_temperature)\n",
    "\n",
    "        if denominator == 0:\n",
    "            display(HTML('<div class=\"card danger\"><b>Stage 3 \u2014 Heater</b><br>'\n",
    "                         '\u274c Water inlet and outlet temperatures cannot be identical.</div>'))\n",
    "            return\n",
    "\n",
    "        water_flow = (milk_flow_rate * cp_milk *\n",
    "                      (target - milk_inlet_temperature)) / denominator\n",
    "\n",
    "        display(HTML(f'<div class=\"card ok\"><b>Stage 3 \u2014 Heater</b><br>'\n",
    "                     f'\ud83d\udd25 Target milk temperature: <b>{target}\u00b0C</b><br>'\n",
    "                     f'\ud83d\udca7 Required hot-water flow: <b>{water_flow:.2f} kg/s</b><br>'\n",
    "                     f'\u2699\ufe0f Heating valve adjusted automatically.</div>'))\n",
    "\n",
    "        # Stage 4\n",
    "        if target >= 72:\n",
    "            display(HTML('<div class=\"card ok\"><b>Stage 4 \u2014 Holding Tube</b><br>'\n",
    "                         '\u2705 Milk reached 72\u00b0C \u2014 15-second pasteurization hold started.</div>'))\n",
    "            progress = widgets.IntProgress(value=0, min=0, max=15,\n",
    "                                            description='Holding:',\n",
    "                                            bar_style='info',\n",
    "                                            layout=widgets.Layout(width='100%'))\n",
    "            display(progress)\n",
    "\n",
    "            for sec in range(1, 16):\n",
    "                time.sleep(0.08)\n",
    "                progress.value = sec\n",
    "\n",
    "            display(HTML('<div class=\"card ok\"><b>Holding complete</b><br>'\n",
    "                         '\u2705 Milk safely held at pasteurization temperature for 15 seconds.</div>'))\n",
    "        else:\n",
    "            display(HTML('<div class=\"card danger\"><b>Stage 4 \u2014 Holding Tube</b><br>'\n",
    "                         '\u274c Temperature below 72\u00b0C \u2014 Flow diverted back to heater.</div>'))\n",
    "            return\n",
    "\n",
    "        # Stage 5\n",
    "        display(HTML('<div class=\"card ok\"><b>Stage 5 \u2014 Cooling</b><br>'\n",
    "                     '\u2744\ufe0f Chilled water entering at 1\u00b0C. Cooling milk to 4\u00b0C.</div>'))\n",
    "        cool_progress = widgets.FloatProgress(value=72, min=4, max=72,\n",
    "                                               description='Milk \u00b0C:',\n",
    "                                               bar_style='info',\n",
    "                                               layout=widgets.Layout(width='100%'))\n",
    "        display(cool_progress)\n",
    "\n",
    "        current = 72\n",
    "        while current > 4:\n",
    "            time.sleep(0.08)\n",
    "            current = max(4, current - 17)\n",
    "            cool_progress.value = current\n",
    "\n",
    "        display(HTML('<div class=\"card ok\"><b>Stage 6 \u2014 Packaging</b><br>'\n",
    "                     '\ud83d\udce6 Milk cooled to 4\u00b0C and forwarded for bottling/carton packaging.<br>'\n",
    "                     '<b>\ud83c\udf89 PROCESS COMPLETED SUCCESSFULLY!</b></div>'))\n",
    "\n",
    "# ============================================================\n",
    "# CONTROL PANEL\n",
    "# ============================================================\n",
    "\n",
    "title = widgets.HTML(\"\"\"\n",
    "<div style=\"font-family:Arial;padding:8px 0\">\n",
    "  <h2 style=\"margin:0\">Plant Control Panel</h2>\n",
    "  <p style=\"margin:4px 0;color:#64748b\">Adjust process inputs and run the simulation.</p>\n",
    "</div>\n",
    "\"\"\")\n",
    "\n",
    "milk_temp = widgets.FloatSlider(value=5, min=0, max=10, step=0.5,\n",
    "                                description='Milk \u00b0C:', continuous_update=False)\n",
    "milk_level = widgets.ToggleButtons(options=[('Low', 0), ('Safe', 1)],\n",
    "                                   value=1, description='Storage:')\n",
    "balance_level = widgets.ToggleButtons(options=[('Low', 0), ('Full', 1)],\n",
    "                                      value=0, description='Balance:')\n",
    "flow = widgets.FloatSlider(value=2.5, min=0.5, max=5, step=0.1,\n",
    "                           description='Flow kg/s:', continuous_update=False)\n",
    "milk_in = widgets.FloatSlider(value=4, min=0, max=20, step=0.5,\n",
    "                               description='Milk inlet:', continuous_update=False)\n",
    "water_in = widgets.FloatSlider(value=85, min=50, max=100, step=1,\n",
    "                                description='Water inlet:', continuous_update=False)\n",
    "water_out = widgets.FloatSlider(value=75, min=40, max=95, step=1,\n",
    "                                 description='Water outlet:', continuous_update=False)\n",
    "\n",
    "run_button = widgets.Button(description='\u25b6 Run Full Simulation',\n",
    "                            button_style='success',\n",
    "                            icon='play',\n",
    "                            layout=widgets.Layout(width='220px', height='42px'))\n",
    "reset_button = widgets.Button(description='\u21ba Reset',\n",
    "                              button_style='warning',\n",
    "                              layout=widgets.Layout(width='120px', height='42px'))\n",
    "output = widgets.Output()\n",
    "\n",
    "def on_run(_):\n",
    "    simulate_plant(milk_temp.value, milk_level.value, balance_level.value,\n",
    "                   flow.value, milk_in.value, water_in.value, water_out.value)\n",
    "\n",
    "def on_reset(_):\n",
    "    milk_temp.value = 5\n",
    "    milk_level.value = 1\n",
    "    balance_level.value = 0\n",
    "    flow.value = 2.5\n",
    "    milk_in.value = 4\n",
    "    water_in.value = 85\n",
    "    water_out.value = 75\n",
    "    output.clear_output()\n",
    "\n",
    "run_button.on_click(on_run)\n",
    "reset_button.on_click(on_reset)\n",
    "\n",
    "controls = widgets.VBox([\n",
    "    title,\n",
    "    widgets.HBox([milk_temp, flow]),\n",
    "    widgets.HBox([milk_level, balance_level]),\n",
    "    widgets.HBox([milk_in, water_in]),\n",
    "    widgets.HBox([water_out]),\n",
    "    widgets.HBox([run_button, reset_button])\n",
    "], layout=widgets.Layout(\n",
    "    border='1px solid #cbd5e1',\n",
    "    padding='16px',\n",
    "    margin='8px 0 16px 0'\n",
    "))\n",
    "\n",
    "display(controls, output)\n",
    "\n",
    "# Run once with the default values\n",
    "simulate_plant()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.x"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
