# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9hoE7lCV7mt8OzYOt10fce466cR6qIZ

flow chart 1
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Figure
fig, ax = plt.subplots(figsize=(8, 11))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.axis('off')


# Rectangle
def draw_box(text, x, y, w=4, h=1, color='#cfe2ff', edgecolor='#084298'):
    rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=10, weight='bold', wrap=True)

# Diamond (
def draw_diamond(text, x, y, w=3.5, h=1.4, color='#fff3cd', edgecolor='#664d03'):
    p1 = [x, y + h/2]
    p2 = [x + w/2, y]
    p3 = [x, y - h/2]
    p4 = [x - w/2, y]
    diamond = patches.Polygon([p1, p2, p3, p4], facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(diamond)
    ax.text(x, y, text, ha='center', va='center', fontsize=9, weight='bold', wrap=True)

def draw_arrow(x1, y1, x2, y2):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="->", color="black", lw=2, mutation_scale=15))

# --- Flowchart  ---

# 1. START
draw_box("START", 3, 10.8, w=4, h=0.7, color='#f8d7da', edgecolor='#842029')

# 2. Read Sensors
draw_arrow(5, 10.8, 5, 9.8)
draw_box("Read milk_temperature &\nmilk_level_sensor", 2, 8.5, w=6, h=1.3, color='#cfe2ff', edgecolor='#084298')

# 3. Decision 1 (Is milk_temperature > 4°C?)
draw_arrow(5, 8.5, 5, 7.5)
draw_diamond("Is milk_temperature\n> 4°C?", 5, 6.7, w=4.0, h=1.6)

# Yes path for Decision 1
draw_arrow(7, 6.7, 7.8, 6.7)
draw_box("Turn ON\nCooling System", 7.8, 6.2, w=1.8, h=1.0, color='#e2e3e5', edgecolor='#41464b')
draw_arrow(8.7, 6.2, 8.7, 4.8) # Down to merge
draw_arrow(8.7, 4.8, 5, 4.8)    # Connect back to main line

# No path goes straight down
draw_arrow(5, 5.9, 5, 4.3)

# 4. Decision 2 (Is milk_level_sensor == 1?)
draw_diamond("Is milk_level_sensor\n== 1?", 5, 3.5, w=4.0, h=1.6)

# Yes path (Left) -> Turn ON Propeller Motor
draw_arrow(3, 3.5, 1.2, 3.5)
draw_box("Turn ON\nPropeller Motor", 0.3, 2.0, w=1.8, h=1.0)
draw_arrow(1.2, 2.0, 1.2, 1.0)
draw_arrow(1.2, 1.0, 3, 1.0) # Connect to END

# No path (Right) -> Turn OFF Propeller Motor & Proceed
draw_arrow(7, 3.5, 8.8, 3.5)
draw_box("Turn OFF\nPropeller Motor", 7.8, 2.0, w=1.9, h=1.0)
draw_arrow(8.75, 2.0, 8.75, 1.3)
draw_box("Proceed to\nBalance Tank", 7.8, 0.4, w=1.9, h=0.9, color='#e2e3e5', edgecolor='#41464b')
draw_arrow(7.8, 0.85, 5.2, 0.85) # Connect to END

# 5. END
draw_box("END", 3.2, 0.5, w=3.6, h=0.7, color='#f8d7da', edgecolor='#842029')

# --- Text labels (Yes / No) ---
ax.text(7.3, 6.8, 'Yes', fontsize=9, va='bottom', weight='bold')
ax.text(5.1, 6.0, 'No', fontsize=9, ha='left', weight='bold')
ax.text(2.5, 3.6, 'Yes', fontsize=9, va='bottom', weight='bold')
ax.text(7.5, 3.6, 'No', fontsize=9, va='bottom', weight='bold')

plt.title("Flowchart 1: Storage Tank Stage (Long Names)", fontsize=12, weight='bold', y=1.02)
plt.savefig('storage_tank_flowchart.png', dpi=300, bbox_inches='tight')
plt.show()

"""flow chart 2"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Figure
fig, ax = plt.subplots(figsize=(7, 9))
ax.set_xlim(0, 10)
ax.set_ylim(0, 10)
ax.axis('off')

# --- Helper Functions ---

# Rectangle
def draw_box(text, x, y, w=4, h=1, color='#cfe2ff', edgecolor='#084298'):
    rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=10, weight='bold', wrap=True)

# Diamond
def draw_diamond(text, x, y, w=4.2, h=1.5, color='#fff3cd', edgecolor='#664d03'):
    p1 = [x, y + h/2]
    p2 = [x + w/2, y]
    p3 = [x, y - h/2]
    p4 = [x - w/2, y]
    diamond = patches.Polygon([p1, p2, p3, p4], facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(diamond)
    ax.text(x, y, text, ha='center', va='center', fontsize=9, weight='bold', wrap=True)

def draw_arrow(x1, y1, x2, y2):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="->", color="black", lw=2, mutation_scale=15))

# --- Flowchart  ---

# 1. START
draw_box("START", 3, 8.8, w=4, h=0.7, color='#f8d7da', edgecolor='#842029')

# 2. Read Sensor
draw_arrow(5, 8.8, 5, 7.8)
draw_box("Read balance_tank_level_sensor", 2, 6.5, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 3. Decision Diamond (Is balance_tank_level_sensor == 1?)
draw_arrow(5, 6.5, 5, 5.5)
draw_diamond("Is balance_tank_level_sensor\n== 1?", 5, 4.5, w=4.5, h=1.6)

# Yes Path (Right) -> Close Inlet Valve -> Maintain Flow
draw_arrow(7.25, 4.5, 8.5, 4.5)
draw_arrow(8.5, 4.5, 8.5, 3.8)
draw_box("Close Inlet Valve", 7.3, 2.8, w=2.4, h=1.0, color='#d1e7dd', edgecolor='#0f5132')

draw_arrow(8.5, 2.8, 8.5, 2.3)
draw_box("Maintain Flow", 7.3, 1.3, w=2.4, h=1.0, color='#e2e3e5', edgecolor='#41464b')
draw_arrow(8.5, 1.3, 8.5, 0.75)
draw_arrow(8.5, 0.75, 6.2, 0.75) # Connect to END line

# No Path (Left/Down) -> Open Inlet Valve
draw_arrow(2.75, 4.5, 1.5, 4.5)
draw_arrow(1.5, 4.5, 1.5, 3.8)
draw_box("Open Inlet Valve", 0.3, 2.8, w=2.4, h=1.0, color='#d1e7dd', edgecolor='#0f5132')
draw_arrow(1.5, 2.8, 1.5, 0.75)
draw_arrow(1.5, 0.75, 3.8, 0.75) # Connect to END line

# 4. END
draw_box("END", 3.8, 0.4, w=2.4, h=0.7, color='#f8d7da', edgecolor='#842029')

# --- Text labels (Yes / No) ---
ax.text(7.6, 4.6, 'Yes', fontsize=10, va='bottom', weight='bold')
ax.text(2.4, 4.6, 'No', fontsize=10, va='bottom', weight='bold')

plt.title("Flowchart 2: Balance Tank Stage (Long Names)", fontsize=12, weight='bold', y=1.02)
plt.savefig('balance_tank_flowchart.png', dpi=300, bbox_inches='tight')
plt.show()

"""flow chart 3"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Figure
fig, ax = plt.subplots(figsize=(8, 11))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.axis('off')

# ---  Helper Functions ---

# Rectangle
def draw_box(text, x, y, w=4, h=1, color='#cfe2ff', edgecolor='#084298'):
    rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=9.5, weight='bold', wrap=True)

# Diamond
def draw_diamond(text, x, y, w=4.2, h=1.5, color='#fff3cd', edgecolor='#664d03'):
    p1 = [x, y + h/2]
    p2 = [x + w/2, y]
    p3 = [x, y - h/2]
    p4 = [x - w/2, y]
    diamond = patches.Polygon([p1, p2, p3, p4], facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(diamond)
    ax.text(x, y, text, ha='center', va='center', fontsize=9, weight='bold', wrap=True)

def draw_arrow(x1, y1, x2, y2):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="->", color="black", lw=2, mutation_scale=15))

# --- Flowchart  ---

# 1. START
draw_box("START", 3, 11.0, w=4, h=0.6, color='#f8d7da', edgecolor='#842029')

# 2. Inputs
draw_arrow(5, 11.0, 5, 10.2)
draw_box("Inputs:\nmilk_flow_rate, milk_inlet_temperature,\nwater_inlet_temperature, water_outlet_temperature", 1.5, 8.8, w=7, h=1.4, color='#cfe2ff', edgecolor='#084298')

# 3. Calculate Fw
draw_arrow(5, 8.8, 5, 8.0)
draw_box("Calculate water_flow_rate using Equation 01", 2, 7.0, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 4. Adjust Heating Valve
draw_arrow(5, 7.0, 5, 6.2)
draw_box("Adjust Heating Valve to water_flow_rate", 2, 5.2, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 5. Check Output Temperature
draw_arrow(5, 5.2, 5, 4.4)
draw_box("Check milk_outlet_temperature", 2, 3.4, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 6. Decision Diamond (Is milk_outlet_temperature >= 72°C?)
draw_arrow(5, 3.4, 5, 2.6)
draw_diamond("Is milk_outlet_temperature\n>= 72°C?", 5, 1.7, w=4.6, h=1.6)

# No Path (Right) -> Divert Back
draw_arrow(7.3, 1.7, 8.2, 1.7)
draw_arrow(8.2, 1.7, 8.2, 1.3)
draw_box("Divert back to\nHeater / Balance Tank", 7.0, 0.3, w=2.4, h=1.0, color='#f8d7da', edgecolor='#842029')
draw_arrow(8.2, 0.3, 8.2, 0.1) # connection line visual indicator

# Yes Path (Down) -> Forward to Holding Tube
draw_arrow(5, 0.9, 5, 0.3)
draw_box("Forward to Holding Tube & END", 1.5, -0.4, w=5, h=0.7, color='#d1e7dd', edgecolor='#0f5132')

# Connect No Path box back to main flow line before END block
draw_arrow(7.0, -0.05, 6.5, -0.05)

# --- Text labels (Yes / No) ---
ax.text(7.5, 1.8, 'No', fontsize=10, va='bottom', weight='bold')
ax.text(5.1, 0.95, 'Yes', fontsize=10, ha='left', weight='bold')

plt.title("Flowchart 3: Heating Stage (Long Names)", fontsize=12, weight='bold', y=1.02)
plt.savefig('heating_stage_flowchart.png', dpi=300, bbox_inches='tight')
plt.show()

"""flow chart 4"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Figure
fig, ax = plt.subplots(figsize=(8, 12))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.axis('off')

# --- Helper Functions ---

# Rectangle
def draw_box(text, x, y, w=4, h=1, color='#cfe2ff', edgecolor='#084298'):
    rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=9.5, weight='bold', wrap=True)

# Diamond
def draw_diamond(text, x, y, w=4.2, h=1.5, color='#fff3cd', edgecolor='#664d03'):
    p1 = [x, y + h/2]
    p2 = [x + w/2, y]
    p3 = [x, y - h/2]
    p4 = [x - w/2, y]
    diamond = patches.Polygon([p1, p2, p3, p4], facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(diamond)
    ax.text(x, y, text, ha='center', va='center', fontsize=9, weight='bold', wrap=True)

def draw_arrow(x1, y1, x2, y2):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="->", color="black", lw=2, mutation_scale=15))

# --- Flowchart  ---

# 1. START
draw_box("START", 3, 11.2, w=4, h=0.5, color='#f8d7da', edgecolor='#842029')

# 2. Input
draw_arrow(5, 11.2, 5, 10.4)
draw_box("Input:\nmilk_temperature_from_heater", 2, 9.2, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 3. First Decision Diamond (Is milk_temperature_from_heater >= 72°C?)
draw_arrow(5, 9.2, 5, 8.2)
draw_diamond("Is milk_temperature_from_heater\n>= 72°C?", 5, 7.2, w=4.8, h=1.6)

# --- NO PATH (Right Branch) ---
draw_arrow(7.4, 7.2, 8.5, 7.2)
draw_arrow(8.5, 7.2, 8.5, 6.6)
draw_box("Trigger Flow Diversion Valve", 7.2, 5.4, w=2.6, h=1.0, color='#f8d7da', edgecolor='#842029')

draw_arrow(8.5, 5.4, 8.5, 4.8)
draw_box("Send back to Balance Tank", 7.2, 3.6, w=2.6, h=1.0, color='#e2e3e5', edgecolor='#41464b')

draw_arrow(8.5, 3.6, 8.5, 3.0)
draw_box("END", 7.5, 2.3, w=2.0, h=0.6, color='#f8d7da', edgecolor='#842029')

# --- YES PATH (Down Branch) ---
draw_arrow(5, 6.4, 5, 5.6)
draw_box("Start 15-Second Timer\n(holding_timer)", 2, 4.4, w=4, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 4. Second Decision Diamond (Timer Complete?)
draw_arrow(5, 4.4, 5, 3.5)
draw_diamond("Timer Complete?", 5, 2.6, w=4.0, h=1.4)

# Timer Complete -> NO Path (Loop Right/Up)
draw_arrow(7.0, 2.6, 7.0, 4.9) # Line up to wait
draw_box("Wait / Continue Flow", 1.8, 2.1, w=2.0, h=0.8, color='#fff3cd', edgecolor='#664d03') # Placement adjust for visual
# Adding loop connector line
draw_arrow(2.8, 4.9, 1.5, 4.9)
draw_arrow(1.5, 4.9, 1.5, 2.5)
draw_arrow(1.5, 2.5, 3, 2.5)

# Timer Complete -> YES Path (Down)
draw_arrow(5, 1.9, 5, 1.1)
draw_box("Forward to Cooler", 3, 0.5, w=4, h=0.6, color='#d1e7dd', edgecolor='#0f5132')

draw_arrow(5, 0.5, 5, 0.1)
draw_box("END", 3.8, -0.4, w=2.4, h=0.5, color='#f8d7da', edgecolor='#842029')

# --- Text labels (Yes / No) ---
ax.text(7.6, 7.3, 'No', fontsize=10, va='bottom', weight='bold')
ax.text(5.1, 6.0, 'Yes', fontsize=10, ha='left', weight='bold')
ax.text(2.6, 1.9, 'No', fontsize=9, va='bottom', weight='bold')  # Loop text adjustment
ax.text(5.1, 1.5, 'Yes', fontsize=10, ha='left', weight='bold')

plt.title("Flowchart 4: Holding Tube Stage (Long Names)", fontsize=12, weight='bold', y=1.02)
plt.savefig('holding_tube_flowchart.png', dpi=300, bbox_inches='tight')
plt.show()

"""flow char 5"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

# 1. Figure
fig, ax = plt.subplots(figsize=(8, 11))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.axis('off')

# ---  Helper Functions ---

# Rectangle
def draw_box(text, x, y, w=4, h=1, color='#cfe2ff', edgecolor='#084298'):
    rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.1", facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(rect)
    ax.text(x + w/2, y + h/2, text, ha='center', va='center', fontsize=9.5, weight='bold', wrap=True)

# Diamond
def draw_diamond(text, x, y, w=4.2, h=1.5, color='#fff3cd', edgecolor='#664d03'):
    p1 = [x, y + h/2]
    p2 = [x + w/2, y]
    p3 = [x, y - h/2]
    p4 = [x - w/2, y]
    diamond = patches.Polygon([p1, p2, p3, p4], facecolor=color, edgecolor=edgecolor, linewidth=2)
    ax.add_patch(diamond)
    ax.text(x, y, text, ha='center', va='center', fontsize=9, weight='bold', wrap=True)

def draw_arrow(x1, y1, x2, y2):
    ax.annotate('', xy=(x2, y2), xytext=(x1, y1),
                arrowprops=dict(arrowstyle="->", color="black", lw=2, mutation_scale=15))

# --- Flowchart ---

# 1. START
draw_box("START", 3, 11.0, w=4, h=0.6, color='#f8d7da', edgecolor='#842029')

# 2. Hot Milk Enters
draw_arrow(5, 11.0, 5, 10.2)
draw_box("Hot Milk Enters at 72°C\n(hot_milk_enters_at_72C)", 2, 9.2, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 3. Chilled Water Enters
draw_arrow(5, 9.2, 5, 8.4)
draw_box("Chilled Water Enters at 1°C\n(chilled_water_enters_at_1C)", 2, 7.4, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 4. Heat Exchange
draw_arrow(5, 7.4, 5, 6.6)
draw_box("Heat Exchange /\nThermal Quench", 2, 5.6, w=6, h=1.0, color='#cfe2ff', edgecolor='#084298')

# 5. Decision Diamond (Is milk_output_temperature <= 4°C?)
draw_arrow(5, 5.6, 5, 4.8)
draw_diamond("Is milk_output_temperature\n<= 4°C?", 5, 3.8, w=4.8, h=1.6)

# No Path (Right) -> Continue Chilling Loop
draw_arrow(7.4, 3.8, 8.5, 3.8)
draw_arrow(8.5, 3.8, 8.5, 3.2)
draw_box("Continue Chilling Loop", 7.2, 2.0, w=2.4, h=1.0, color='#fff3cd', edgecolor='#664d03')
draw_arrow(8.5, 2.0, 8.5, 1.3)
draw_arrow(8.5, 1.3, 5, 1.3) # Connect back to main flow line

# No Path feedback loop indicator (Optional but good for logic)
draw_arrow(7.2, 2.5, 6.5, 2.5)

# Yes Path (Down) -> Forward to Packager
draw_arrow(5, 3.0, 5, 1.8)
draw_box("Forward to Packager", 2, 0.5, w=6, h=1.0, color='#d1e7dd', edgecolor='#0f5132')

# 6. END
draw_arrow(5, 0.5, 5, -0.1)
draw_box("END", 3.5, -0.8, w=3, h=0.6, color='#f8d7da', edgecolor='#842029')

# --- Text labels (Yes / No) ---
ax.text(7.6, 3.9, 'No', fontsize=10, va='bottom', weight='bold')
ax.text(5.1, 2.7, 'Yes', fontsize=10, ha='left', weight='bold')

plt.title("Flowchart 5: Cooling Stage (Long Names)", fontsize=12, weight='bold', y=1.02)
plt.savefig('cooling_stage_flowchart.png', dpi=300, bbox_inches='tight')
plt.show()